name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - run: |
        cmake -S . -B build/
        cmake --build build/
        cd build/ && ctest
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        extensions: 'h,hpp,cpp,c,ino'
        clangFormatVersion: 12